version: 2

project_name: invoices

builds:
  - id: invoices
    main: ./cmd/invoices/main.go
    binary: invoices
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    files:
      - README.md
      - LICENSE
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  github:
    owner: williamveith
    name: automaticarchival 