version: 2

project_name: invoices

before:
  hooks:
    - rm -f README.md LICENSE.md || true
    
builds:
  - id: invoices
    main: ./cmd/invoices/main.go
    binary: invoices
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  github:
    owner: williamveith
    name: automaticarchival
