name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Clean up Git state
        run: |
            git config --global user.email "actions@github.com"
            git config --global user.name "github-actions"
            git add .
            git commit -m "chore: clean up before release" || echo "No changes to commit"
            git push origin $(git rev-parse --abbrev-ref HEAD) || echo "No changes to push"
  

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.2'

      - name: Install GoReleaser
        run: |
          curl -sL https://github.com/goreleaser/goreleaser/releases/latest/download/goreleaser_Linux_x86_64.tar.gz | tar xz
          mv goreleaser /usr/local/bin/

      - name: Run GoReleaser
        run: goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

